language:
  - node_js

before_install:
  - npm install -g gulp
  - npm install

before_script:
  - npm install -g bower
  - bower install

branches:
  only:
    - master

notifications:
  email:
    - varitpatel@gmail.com
